name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment5-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Fix GitHub SSH known_hosts
            run: |
              ssh-keygen -R github.com || true
              ssh-keyscan github.com >> ~/.ssh/known_hosts
          - name: Debug - check Image presence
            run: |
                echo "Listing output/images contents:"
                ls -lh buildroot/output/images/ || true
          - name: Check port 9000
            run: |
                if lsof -i :9000; then
                  echo "Port 9000 is in use, killing process..."
                  sudo fuser -k 9000/tcp
                else
                  echo "Port 9000 is free"
                fi
          - name: Check SSH port 10022
            run: |
                if lsof -i :10022; then
                  echo "Port 10022 is in use, killing process..."
                  sudo fuser -k 10022/tcp
                else
                  echo "Port 10022 is free"
                fi
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
